config/routes.rb
Rails.application.routes.draw do
  root to: "bookings#index"
  devise_for :users
  get 'dashboard', to: 'pages#dashboard'
  resources :cars, only: ['show']
  resources :bookings
  get '', to: 'pages#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :giver_car, class_name: "Car"
  belongs_to :taker_car, class_name: "Car", optional: true
  belongs_to :parking

  validates :available_at, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user

  has_many :givings, class_name: "Booking", foreign_key: :giver_car_id, dependent: :destroy
  has_many :takings, class_name: "Booking", foreign_key: :taker_car_id, dependent: :destroy
end

app/models/parking.rb
class Parking < ApplicationRecord
  has_many :bookings, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :address, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cars, dependent: :destroy
  has_many :givings, through: :cars, foreign_key: :giver_car_id
  has_many :takings, through: :cars, foreign_key: :taker_car_id
  # has_many :received_bookings, through: :cars, foreign_key: :taker_car_id, source: :car
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @current_lat = nil
    @current_lng = nil
    if params[:query].present?
      @parkings = Parking.near(params[:query], 0.5)
                         .joins(:bookings)
                         .where(bookings: { taker_car: nil })
                         .distinct
                        #  .where("bookings.available_at BETWEEN ? AND ?", params[:time] - 10.minutes, params[:time] + 10.minutes)
      # @destination = Parking.create(address: params[:query]).to_a
      # @parkings = @parkings.to_a
      # @parkings.push(@destination)
    else
      @parkings = Parking.all
    end

    @markers = @parkings.geocoded.map do |parking|
      {
        lat: parking.latitude,
        lng: parking.longitude,
        parkingId: parking.id
      }
    end

    if params[:lat].present?
      @current_lat = params[:lat].to_f
      @current_lng = params[:lng].to_f
    end

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: "bookings/list", locals: { parkings: @parkings }, formats: [:html] }
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @parking = @booking.parking
    @parking.geocode
    @markers = [{
      lat: @parking.latitude,
      lng: @parking.longitude
    }]
  end

  def new
    @booking = Booking.new
    @parking = current_user.cars.last&.takings&.order(available_at: :desc)&.first&.parking

    redirect_to root_path if @parking.nil?
  end

  def create
    @parking = current_user.cars.last.takings.last.parking
    user_entry_datetime = Time.zone.parse(review_params_booking[:available_at])
    @booking = Booking.new({ available_at: user_entry_datetime })
    @booking.giver_car = current_user.cars.last
    @booking.parking = @parking
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(taker_car: current_user.cars.last)
    BookingChannel.broadcast_to(
      @booking,
      render_to_string(partial: "show_giver", locals: {booking: @booking})
    )
    redirect_to booking_path(@booking)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  private

  def review_params_booking
    params.require(:booking).permit(:available_at)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def show
    # @car = Car.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
    @bookings = current_user.takings
  end
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/meta_tags_helpers.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/bookings/_list.html.erb
<div class="booking-cards-container" data-map-target="list">
  <% parkings.each do |parking| %>
    <% booking = parking.bookings.last%>

    <div class="booking-card" id="parking-<%= parking.id %>">

      <div class="bk-card-img">
        <%= image_tag("cars/new-map-car.png", width: 40, height: 20, crop: :fill) %>
      </div>

      <div class="bk-card-infos">
        <span class="index-card-text">
          libre dans <%= time_ago_in_words booking.available_at %>
        </span>
      </div>

      <div class="bk-card-go-btn">
        <%= link_to booking_path(booking), class:"bk-card-eye-btn" do %>
          <i class="fa-sharp fa-solid fa-eye" style="color: #000000;"></i>
        <% end %>
      </div>

    </div>

  <% end %>

</div>

app/views/bookings/_show_giver.html.erb
<div data-controller="booking-subscription"
  data-booking-subscription-booking-id-value='<%= booking.id %>'>
  <% if booking.taker_car.present? %>
    <div class="booking-cards-container-show4">
      <div class="dark-container">
        <div class="booking-card">
          <div class="index-card-text">
            <span><%=  booking.taker_car.user.first_name %></span>
            <span>récupère votre place dans </span>
            <span><%= time_ago_in_words booking.available_at %></span>
          </div>
        </div>

        <div class="booking-card">
          <div class="address-card-text mb-0">
            <span>📍 <%= @booking.parking.address %></span>
            <%# <span>Localiser la place dans GoogleMap : </span> %>
          </div>
        </div>
        <div class="booking-card mb-2">
          <%= link_to "https://google.fr/maps/place/#{@booking.parking.address}", target: "_blank" do %>
            <%= image_tag('gmap.png',width: 30, height: 30, crop: :fill ) %>
            <%# <i class="fa fa-map-marker" aria-hidden="true"></i> %>
          <% end %>
        </div>
        <div class="booking-card">
          <div class="bk-card-infos">
            <div class="bk-card-img2">
              <%= image_tag("cars/new-map-car.png", width: 40, height: 20, crop: :fill) %>
            </div>
              <span class="index-card-text"><%= @booking.taker_car.car_type %></span>
          </div>

          <div class="bk-card-infos">
            <span class="index-card-text"><%= @booking.taker_car.car_model %>
            <%= @booking.taker_car.car_color %></span>
            <span class="index-card-text"><strong><%= @booking.taker_car.plate %></strong></span>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <div class="booking-cards-container-show2">
      <div class="booking-card-show">

        <div class="index-card-text-show">
          <h2> On cherche ton Relay! </h2>
          <div class="spinner-grow flex" role="status"
            data-controller="booking-subscription"
            data-booking-subscription-booking-id-value=<%= booking.id %>>
            <span class="sr-only">Loading...</span>
          </div>
        </div>
        
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/index.html.erb
<%= render "shared/header" %>

<div
  data-controller="map"
  data-map-query-value="<%= params[:query] %>"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
  data-map-redimage-value="<%= asset_path("red.png") %>"
  data-map-blueimage-value="<%= asset_path("blue.png") %>"
  data-map-flagimage-value="<%= asset_path("destination.png") %>"
>
  <div class="map">
    <div class="map-container" data-map-target="map">

      <%= form_with url: bookings_path, method: :get, class: "map-search-fields-container" do %>
        <div
          class="map-address-field"
          data-controller="autocomplete"
          data-autocomplete-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
        >
          <%=
            text_field_tag :query,
                           params[:query],
                           placeholder: "Adresse",
                           data: {
                             autocomplete_target: "inputaddress",
                           },
                           class: "d-none"
          %>

          <div data-autocomplete-target= "input">
          </div>
        </div>

        <div class="map-time-and-btn-container">
          <div>
            <%=
              text_field_tag :time,
                             params[:time],
                             class: "map-time-field",
                             placeholder: "Time",
                             type: "time",
                             value: Time.current.strftime('%H:%M')
            %>
          </div>

          <%= submit_tag "Go", class: "map-go-btn" %>
        </div>
      <% end %>
    </div>
  </div>

  <%= render "list", parkings: @parkings %>
</div>

<%= render "shared/navbar" %>

app/views/bookings/new.html.erb
<%= render "shared/header" %>

  <div class="new-container">
    <div class="booking-cards-container-show5">
    
      <div class="form-booking">

        <div class="adress-box">
          <h3>Je suis garé au&nbsp;: </h3>
          <p> 📍 <%= @parking.address %> </p>
        </div>


        <div class="datetime-box">
          <h4>Je souhaite libérer cette place à&nbsp;:</h4>
            <%= simple_form_for @booking do |f| %>
              <%= f.input :available_at, label: false, as: :datetime, html5: true, input_html:{value: 5.minutes.from_now.strftime('%Y-%m-%dT%k:%M')} %>
              <%= f.submit "CHERCHER UN RELAY", class: "new-btn" %>
            <% end %>
        </div>

      </div>
    </div>
  </div>


<%= render "shared/navbar" %>

app/views/bookings/show.html.erb
<%= render "shared/header" %>

  <div class="map-container"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
    data-map-blueimage-value="<%= asset_path("blue.png") %>">
    <div class="map-container"
      data-map-target="map">
    </div>
  </div>


  <% if @booking.taker_car == current_user.cars.last %>

    <div class="booking-cards-container-show5">

      <div class="dark-container-show4">

        <div class="show-card-first-box">
          <span class="card-text"><%=  @booking.giver_car.user.first_name%></span>
          <span class="card-text">vous attend dans </span>
          <span class="card-important"><%= time_ago_in_words @booking.available_at%></span>
        </div>

        <div class="address-card-text">
          <%= image_tag "parking.png", class: "icon" %>
          <span class="address"><%= @booking.parking.address %></span>
        </div>

        <div class="show-card-third-box-b">
          <%= link_to "https://google.fr/maps/place/#{@booking.parking.address}", target: "_blank" do %>
            <%= image_tag('gmap.png',width: 30, height: 30, crop: :fill ) %>
          <% end %>
        </div>


        <div class="show-card-fourth-box-b">

          <div class="img-type">
            <div class="bk-card-img2">
              <%= image_tag("cars/new-map-car.png", width: 40, height: 20, crop: :fill) %>
            </div>
            <span class="index-card-text"><%= @booking.giver_car.car_type %></span>
          </div>

          <div class="model-color">
            <span class="index-card-text"><%= @booking.giver_car.car_model %></span>
            <span class="index-card-text"><%= @booking.giver_car.car_color %></span>
          </div>

          <span class="index-card-text"><strong><%= @booking.giver_car.plate %></strong></span>

        </div>

        </div>

        <%= link_to "JE SUIS BIEN GARÉ(E)", bookings_path, class: "new-btn" %>

      </div>

    </div>


  <% elsif @booking.giver_car == current_user.cars.last %>
    <%= render "show_giver", booking: @booking %>






  <% else %>

    <div class="booking-cards-container-show1">

      <div class="dark-container-show3">

        <div class="show-card-first-box">
          <%= image_tag "parking.png", class: "icon" %>
          <i class="fa-solid fa-person-walking">.....</i>
          <span> 200 m📍 </span>
        </div>

        <div class="show-card-second-box">
          <%= image_tag "parking.png", class: "icon" %>
          <span class="card-text"> dans  </span>
          <span class="card-text"><%= time_ago_in_words @booking.available_at%></span>
        </div>

        <div class="address-card-text">
          <%= image_tag "parking.png", class: "icon" %>
          <span class="address"><%= @booking.parking.address %></span>
        </div>

        <div class="show-card-fourth-box">

          <div class="show-card-car-infos-1">
              <div class="bk-card-img2">
                <%= image_tag("cars/new-map-car.png", width: 40, height: 20, crop: :fill) %>
              </div>
              <span class="index-card-text"><%= @booking.giver_car.car_type %></span>
              <span class="index-card-text"><%= @booking.giver_car.car_model %></span>
              <span class="index-card-text"><%= @booking.giver_car.car_color %></span>
          </div>

        </div>

        <%= link_to "RESERVER", booking_path, data: {turbo_method: :patch},  class: "new-btn" %>

      </div>

    </div>
  <% end %>

<%= render "shared/navbar" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Abel&family=Monomaniac+One&family=Sarabun&display=swap" rel="stylesheet">

    <%= favicon_link_tag "favicon.png", rel: "icon", type: "image/png" %>


    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

        <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>">
    <meta property="og:type" content="https://www.relayapp.fun">
    <meta property="og:url" content="<%= request.original_url %>">
    <meta property="og:image" content="<%= meta_image %>">
    <meta property="og:description" content="<%= meta_description %>">
    <meta property="og:site_name" content="<%= meta_title %>">

      <meta name="apple-mobile-web-app-capable" content="yes">
      <meta name="mobile-web-app-capable" content="yes">
       <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">

    <%= render 'shared/ios_pwa_links' %>

  </head>

  <body>

      <%= yield %>

  </body>
</html>

app/views/pages/dashboard.html.erb
<%= render "shared/header" %>

<div class="base-container">
  <div class="show-infos-container">
    <h2>Tous mes relays</h2>
    <% @bookings.each do |booking| %>
      <div class="d-flex justify-content-between align-items-center">
        <% if booking.giver_car.car_type == "citadine" %>
          <%= image_tag("cars/citadine.png", width: 50, height: 50, crop: :fill) %>
        <% elsif booking.giver_car.car_type == "berline" %>
          <%= image_tag("cars/berline.png", width: 50, height: 50, crop: :fill) %>
        <% elsif booking.giver_car.car_type == "van" %>
          <%= image_tag("cars/van.png", width: 50, height: 50, crop: :fill) %>
        <% end %>

        <div>
          <h3><%= booking.giver_car.user.first_name%> <%= booking.giver_car.user.last_name%></h3>
          <p>Le relay s'est passé <%= time_ago_in_words booking.available_at%></p>
          <p>à l'adresse <%= booking.parking.address %></p>
          <p><strong><%= booking.giver_car.plate%></strong></p>
        </div>

        <div>
          <p><%= booking.giver_car.car_model%></p>
          <p><%= booking.giver_car.car_type%></p>
          <p> <%= booking.giver_car.car_color%></p>

          <%= link_to "Voir les détails", booking_path(booking), class: 'button-blue-big'%>

        </div>
      </div>
    <% end %>
  </div>
</div>

<%= render "shared/navbar" %>

app/views/shared/_header.html.erb
 <div class="header-container">
    <p class="btn-logo"><%= image_tag 'cars/new-map-car.png' %></p>
    <p >RE</p>
    <p ><i class="fa-solid fa-arrow-right px-1" style="color: #E8FF54"></i></p>
    <p >LAY</p>
  </div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar-container">
  <nav class="navbar">

    <%= link_to bookings_path, class: "navbar-style" do %>
      <div class="navbar-round-btn">
        <i class="fa-sharp fa-solid fa-house" style="color: #000000;"></i>
      </div>
    <% end %>

    <%= link_to new_booking_path, class: "navbar-style" do %>
      <div class="navbar-round-btn">
        <i class="fa-solid fa-car-side" style="color: #000000;"></i>
      </div>
    <% end %>


    <%= link_to destroy_user_session_path, class: "navbar-style", data: {turbo_method: :delete} do %>
        <i class="fa-solid fa-user" style="color: #000000;"></i>
    <% end %>

  </nav>
</div>